:time_estimate: 11

= Lab: Provision Edge Devices Using Custom Installation Media

_Estimated reading time: *{time_estimate} minutes*._

Objective::
Provision edge devices in a disconnected environment by using a customized RHEL installation media.

WARNING: Work in progress

== Before you Begin

You need a _development machine_ running RHEL, to which you have unrestricted sudo access.
The _development machine_ has access to mirrors of RHEL package repositories and bootc container images.

These instructions were tested on RHEL 10.0 but should work with minimal or no changes on newer and older RHEL releases, since 9.6.

If you are using the course classroom, log in on the `workstation` VM as the user `student` with password `student`.
If not, please adapt the instructions to your test environment.

Make sure you verified your test environment by following the xref:TBD[first lab] of this course.

== Instructions

You will use the bootc image builder utility to create a custom installation ISO, which embeds a bootc container image and a kickstart script for unattended installation, and use that custom ISO as a virtual DVD disk to install RHEL in a new VM.

1. Prepare to start this activity by checking that you have the outcomes from previous activities.

.. If needed, create a local clone of the sample code repository of this course, but do NOT enter its directory.
Stay on your home directory to start this lab.
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *git clone https://github.com/RedHatQuickCourses/rhde-bootc-samples.git*
Cloning into 'rhde-bootc-samples'...
...
--

.. If needed, login to your private registry.
+
[source,subs="verbatim,quotes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
--

.. Verify that you have a bootc container image named `httpd-system:v1.0` in your private container registry.
If you do not, please perform the xref:TBD[first lab], which builds and publishes that image.
+
[source,subs="verbatim,quotes"]
--
$ *skopeo inspect --format '{{ json .RepoTags }}' docker://registry.lab.example.com:5000/httpd-system:v1.0*
["v1.0"]
--

.. Verify that you have access to libvirt through its session interface.
If you do not, please perform the preparation tasks from the xref:TBD[first lab].
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name   State
--------------------

--
+
NOTE: It is fine if you have some local VMs on your system, as long as there isn't a VM named `bootc-iso`.

2. Prepare scripts and configuration files you will use to automate creating and testing an installation ISO.

.. Create a working directory and copy the sample files to it.
Then make the temporary working directory your current directory.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir temp-test-iso*
$ **cp rhde-bootc-samples/bib-iso/* temp-test-iso** 
$ *cd temp-test-iso*
--

.. Review the example bootc image builder TOML file named `config.toml`.
+
Its only content is an embedded Anaconda kickstart script.
Notice that the kickstart script does NOT include an `ostreecontainer` command, but it configures the following:
+
--
... Locale, keyboard, and other system settings so the installation can proceed unatended.
+
... A new partition table, with default automatic partitioning for RHEL.
+
... Dynamic network configuaration, using DHCP.
+
... A user named `core` with password `redhat123` and an SSH key.
+
... The hostname `bootc-iso`, so you can easily distinguish a terminal in a _test VM_ from a terminal in your _development machine_.
--
+
[source,subs="verbatim,quotes"]
--
include::1@samples:bib-iso:example$config.toml[]
--

.. Create an SSH key for use with your test VM and embed it in your TOML file.
+
[source,subs="verbatim,quotes"]
--
$ *ssh-keygen -N '' -f edge-key -C 'initial key for edge devices'*
Generating public/private rsa key pair.
...
$ *SSH_PUB_KEY=$( cat edge-key.pub )*
$ *sed -i "s|REPLACE_WITH_SSH_PUB_KEY|$SSH_PUB_KEY|" config.toml*
--

.. Review the `bib-iso.sh` script which invokes the bootc image builder utility, and which takes the former file as input.
+
Make sure you can distinguish between command-line options and arguments for Podman from command-line options and arguments for bootc image builder.
+
--
... Podman runs from the `root` user and creates a privileged container, which has access to host namespaces.
+
... Podman mounts the container storage of the root user, to where your bootc container image was already pulled.
+
... Podman mounts the output folder and TOML file so bootc image builder has access to them.
+
... Podman pulls bootc image builder from our private registry.
+
... Bootc image builder creates an ISO image and uses a TOML file to pick its kickstart script.
+
... Bootc image builder uses the `httpd-system:v1.0` container image, which was previously pulled.
--
+
[source,subs="verbatim,quotes"]
--
include::1@samples:bib-iso:example$bib-iso.sh[]
--

.. Review the `virt-install.sh` script which creates a test VM.
+
It is designed to be run in text mode, so you do not need to switch to a graphical console or remote desktop session just to view the test VM boot screens, by setting the following options:
+
--
... User mode networking with the Passt provider and port-forwarding to enable network connections from your _development machine_ to services running inside the _test VM_.
... Direct kernel loading (the `--location` option) to grab the Linux kernel and initial RAM disk from your ISO image.
... Kernel command-line arguments to use the kickstart file from your ISO image.
... A serial console, so boot messages display in the current terminal, which could be an SSH session.
--
+
[source,subs="verbatim,quotes"]
--
include::1@samples:bib-iso:example$virt-install.sh[]
--
+
NOTE: Depending on the version of your bootc image builder image, you may be able to use `--location` without specifying the paths to the kernel and the initial RAM disk.
+
//REF: https://issues.redhat.com/browse/HMS-6054

3. Create a custom installation ISO.

.. Log in again on your private registry, but this time as the root user.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
--

.. Download the bootc container image to the container storage of the root user.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman pull registry.lab.example.com:5000/httpd-system:v1.0*
...
Writing manifest to image destination
...
--

.. Create an output directory for the bootc image builder utility.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir output*
--

.. Invoke the script which runs the bootc image builder utility.
+
Be patient, it takes several minutes running.
+
[source,subs="verbatim,quotes"]
--
$ *bash bib-iso.sh*
...
Message: Results saved in .
--

.. Copy the installable ISO from the bootc image builder output directory to a more permanent location, and give it an easily identifiable name.
That file would be distributed to personel responsible for installing actual edge devices.
+
[source,subs="verbatim,quotes"]
--
$ *cp output/bootiso/install.iso httpd-system.iso*
--

.. If you need to rebuild your installation ISO, for whatever reason, we recommend that you first clean your bootc image builder output directory.
+
[source,subs="verbatim,quotes"]
--
$ **sudo rm -rf output/***
--

4. Inspect your custom ISO installer image, to confirm that it includes your kickstart file and your bootc container image.

.. Mount the generated ISO image.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir temp-iso*
$ *sudo mount -o loop,ro httpd-system.iso temp-iso*
--

.. Verify that there are two kickstart scripts inside the iso
+
[source,subs="verbatim,quotes"]
--
$ **ls temp-iso/*ks**
temp-iso/osbuild-base.ks  temp-iso/osbuild.ks
--

.. Verify that your kickstart script contents are in the `osbuid.ks` file and it includes the `osbuild-base.ks` file.
+
[source,subs="verbatim,quotes"]
--
$ *head -n 5 temp-iso/osbuild.ks*
%include /run/install/repo/osbuild-base.ks
include::1@samples:bib-iso:example$config.toml[lines=2..5]
--

.. Verify that the included `osbuild-base.ks` file provides the `ostreecontainer` command.
It also provides a `%post` script that changes the bootc container image reference from the installation media to the reference given to bootc image builder. 
+
[source,subs="verbatim,quotes"]
--
$ *head -n 3 temp-iso/osbuild-base.ks*
ostreecontainer --url=/run/install/repo/container --transport=oci
%post --erroronfail
bootc switch --mutate-in-place --transport registry registry.lab.example.com:5000/httpd-system:v1.0
--

.. Umount the generated ISO image.
+
[source,subs="verbatim,quotes"]
--
$ *sudo umount temp-iso*
--

5. To demonstrate that the custom installation media works in a disconnected environment, stop the private registry in the virtual labs environment.

.. On a new terminal, open an SSH session to the `utility` VM.
In the classroom environment, The `registry` host name is an alias to the `utility` server.
The `student` user is pre-configured to passwordless SSH access and with `sudo` rights.
+
[source,subs="verbatim,quotes"]
--
$ *ssh utility*
--

.. Alternatively, you can open a console to the `utility` VM and log in as the `student` user.

.. Stop the `registry` service.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl stop registry*
--

.. Keep this terminal open and its SSH session, because you will return to it in the end of this activity.


6. Install RHEL in a local VM, using the custom installation ISO, without acessing the container registry.

.. Verify that your _development machine_ cannot access the private registry anymore.
+
[source,subs="verbatim,quotes"]
--
$ *podman search registry.lab.example.com:5000/*
Error: 1 error occurred:
        * couldn't search registry "registry.lab.example.com:5000": pinging container registry registry.lab.example.com:5000: Get "http://registry.lab.example.com:5000/v2/": dial tcp 172.25.250.220:5000: connect: connection refused
--

.. Set an environment variable with the disk label of your generated ISO image.
It is required by the kernel arguments on the `virt-install.sh` script.
+
[source,subs="verbatim,quotes"]
--
$ *iso-info httpd-system.iso | grep Volume*
Volume      : RHEL-10-0-BaseOS-x86_64
$ *export LABEL=RHEL-10-0-BaseOS-x86_64*
--

.. Invoke the script which creates a _test VM_ from the ISO.
+
After the installation is complete and the VM reboots, detattch from its virtual serial console using kbd:[Ctrl+C].
+
[source,subs="verbatim,quotes"]
--
$ *bash virt-install.sh*
...
[  114.660806] reboot: Restarting system

Domain creation completed.
Restarting guest.
Running text console command: virsh --connect qemu:///session console bootc-iso
Connected to domain 'bootc-iso'
Escape character is ^] (Ctrl + ])
--

.. Alternatively, you can use the `virt-install-gui.sh` script, which requires a Linux graphical desktop to display the VM console.
This script boots the VM from the ISO file as a virtual CD-ROM drive, by using the `--cdrom` option instead of the `--location` option, so it uses the bootloader on the ISO image itself, like a physical device would do from physical media.

.. If something goes wrong and you have to retry creating your VM, first stop and delete it.
+
[source,subs="verbatim,quotes"]
--
$ *virsh destroy bootc-iso*
Domain 'bootc-iso' destroyed
$ *virsh undefine bootc-iso --remove-all-storage*
Domain 'bootc-iso' has been undefined
Volume 'vda'(/home/student/.local/share/libvirt/images/bootc-iso.qcow2) removed.
--

7. Verify that the test VM runs a web server with the mock web application files.

.. Use the SSH hey to access your _test VM_.
+
[source,subs="verbatim,quotes"]
--
$ *ssh -i edge-key -p 8022 core@127.0.0.1*
...
[core@bootc-iso ~]$
--

.. Verify that your _test VM_ was provisioned using image mode.
The password for the `core` user is `redhat123`.
+
[source,subs="verbatim,quotes"]
--
$ *sudo bootc status*
● Booted image: registry.lab.example.com:5000/httpd-system:v1.0
        Digest: sha256:068dc70b8eca43a0fa3c4a436d7098305898e5235c677f489b69ddc370885f6d
       Version: 10.0 (2025-08-15 21:23:47.500494502 UTC)
--

.. Verify that the Apache Web Server is active is your _test VM_ and .
+
[source,subs="verbatim,quotes"]
--
$ *systemctl is-active httpd*
active
$ *curl 127.0.0.1*
This would be the HTML and Javascrit code of your single-page web application.
--

.. Terminate the SSH session to your _test VM_ and verify that the host can also access the mock web application, through  port-forwarding, similar to how SSH access works.
+
[source,subs="verbatim,quotes"]
--
$ *exit*
active
$ *curl 127.0.0.1:8080*
This would be the HTML and Javascrit code of your single-page web application.
--

8. Before continuing with this course, restart your private registry.

.. Return to the terminal with an open SSH session to the `utility` machine.

.. Start the `registry` service.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl start registry*
--

.. You can now close your SSH session to the `utility` VM and verify that your _development machine_ can access the private registry again.
+
[source,subs="verbatim,quotes"]
--
$ *exit*
$ *podman search registry.lab.example.com:5000/*
NAME                                                                  DESCRIPTION
registry.lab.example.com:5000/httpd-system
...
--

9. Stop your _test VM_ to free local TCP ports for the next lab.
+
[source,subs="verbatim,quotes"]
--
$ *virsh destroy bootc-iso*
Domain 'bootc-iso' destroyed
--

What you did with a VM here, you could do with a physical machine.
You would use the https://github.com/FedoraQt/MediaWriter/releases[Fedora Media Writer] or a similar tool to write your custom ISO image to USB media, and use the BIOS screens of your machine to boot from USB media.

== What's next

The next chapter shows how to bootc image builder to build a cloud image and how to use cloud-init to perform day-1 customizations of virtual edge devices and edge cloud instances.
